Error at scroll_to_end_of_the_page, attempt 1/3: HTTPConnectionPool(host='localhost', port=54159): Max retries exceeded with url: /session/2629162be5c16084a5e049e3a6db3041/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109519910>: Failed to establish a new connection: [Errno 61] Connection refused'))
Error at scroll_to_end_of_the_page, attempt 2/3: HTTPConnectionPool(host='localhost', port=54159): Max retries exceeded with url: /session/2629162be5c16084a5e049e3a6db3041/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10951b530>: Failed to establish a new connection: [Errno 61] Connection refused'))
Error at scroll_to_end_of_the_page, attempt 3/3: HTTPConnectionPool(host='localhost', port=54159): Max retries exceeded with url: /session/2629162be5c16084a5e049e3a6db3041/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109565460>: Failed to establish a new connection: [Errno 61] Connection refused'))
Error at process_comic_chapters, attempt 1/3: No active exception to reraise
